@domain = http://localhost:4004

##insert otp 
POST {{domain}}/catalog/Z_GB_TPO_OTP
Content-Type: application/json

{
    "Request_Id" : "1000000034",
    "OTP":"123"

}

###Send OTP in Email
POST {{domain}}/catalog/SendOTPInEmail
Content-Type: application/json

{
    "TPO_Req_No" : "1000000034"

}

### Verify OTP
POST {{domain}}/catalog/verifyOTP
Content-Type: application/json

{
    "TPO_Req_No" : "1000000034",
    "OTP" : "25854337"

}